### ISSUE TITLE
Access denied to part of package

### ISSUE THREAD

**Issue by w33n** [sboulema/mtgGoldfish#1]
Access to script at 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js' from origin 'http://ip-address' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by sboulema** [comment]
Thanks for reporting!

Sorry for the huge delay...
Should be fixed in the new release 🚀
